apiVersion: v1
kind: Service
metadata:
  name: cfg
  namespace: ccoms
  labels:
    app: cfg-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: cfg-ms
---
apiVersion: v1
kind: Service
metadata:
  name: emp
  namespace: ccoms
  labels:
    app: emp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: emp-ms
---
apiVersion: v1
kind: Service
metadata:
  name: dept
  namespace: ccoms
  labels:
    app: dept-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: dept-ms
---
apiVersion: v1
kind: Service
metadata:
  name: org
  namespace: ccoms
  labels:
    app: org-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: org-ms
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ccoms
  labels:
    app: proxy-svc
spec:
  ports:
  - port: 8111
    protocol: TCP
  selector:
    app: proxy-ms
