## PROD

PROD_ANSIBLE_HOST=""
PROD_ANSIBLE_USER=""
PROD_ANSIBLE_PASSWORD=""
PROD_K8S_HOST=""
PROD_K8S_USER=""
PROD_K8S_PASSWORD=""

## UAT

UAT_ANSIBLE_HOST=""
UAT_ANSIBLE_USER=""
UAT_ANSIBLE_PASSWORD=""
UAT_K8S_HOST=""
UAT_K8S_USER=""
UAT_K8S_PASSWORD=""


## QA

QA_ANSIBLE_HOST=""
QA_ANSIBLE_USER=""
QA_ANSIBLE_PASSWORD=""
QA_K8S_HOST=""
QA_K8S_USER=""
QA_K8S_PASSWORD=""

## DEV

DEV_ANSIBLE_HOST="vl-aus-rem-dv3l"
DEV_ANSIBLE_USER="root"
DEV_ANSIBLE_PASSWORD=""
DEV_K8S_HOST="vl-aus-rem-dv3l"
DEV_K8S_USER="root"
DEV_K8S_PASSWORD="bmcAdm1n"

## UAT-2

UAT_2_ANSIBLE_HOST=""
UAT_2_ANSIBLE_USER=""
UAT_2_ANSIBLE_PASSWORD=""
UAT_2_K8S_HOST=""
UAT_2_K8S_USER=""
UAT_2_K8S_PASSWORD=""
